[package]
name = "glyph_brush"
version = "0.5.0"
authors = ["Alex Butler <alexheretic@gmail.com>"]
edition = "2018"
description = "Fast cached text render library using rusttype"
repository = "https://github.com/alexheretic/gfx-glyph"
keywords = ["font", "ttf", "truetype", "text"]
license = "Apache-2.0"
readme="README.md"

[dependencies]
glyph_brush_layout = { version = "0.1.5", path = "../glyph-brush-layout" }
log = "0.4.4"
ordered-float = "1"
full_rusttype = { version = "0.7.7", features = ["gpu_cache"], package = "rusttype" }
hashbrown = "0.4"
twox-hash = "1"

[dev-dependencies]
env_logger = { version = "0.6", default-features = false }
lazy_static = "1"
gl = "0.12"
glutin = "0.21"
spin_sleep = "0.3"
